config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for locale
  put 'locales/:locale', to: 'locales#update', as: :locale,
                         constraints: { locale: /#{I18n.available_locales.join('|')}/ }

  # Regular routes
  get 'welcome', to: 'welcome_pages#welcome', as: :welcome
  get 'about', to: 'welcome_pages#about', as: :about
  get 'contacts', to: 'welcome_pages#contacts', as: :contacts

  concern :attachable do
    resources :attachments, only: :create
  end
  resources :attachments do
    member do
      post 'add_attachment_to_album'
    end
  end
  resources :albums, concerns: [:attachable]

  # Resource routes
  resources :posts
  resources :locations
  resources :important_dates

  # Invitations routes
  get 'invitations', to: 'invitations#index', as: :invitations

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'welcome_pages#welcome', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/shared/_breadcrumbs.html.slim
- if @breadcrumbs
  nav.main-breadcrumb aria-label="breadcrumb" 
    ol.breadcrumb
      - @breadcrumbs.each do |breadcrumb|
        - if breadcrumb[:path].nil?
          li.font-weight-bold.breadcrumb-item.text-muted aria-current="page"
            = breadcrumb[:label]
        - else
          li.breadcrumb-item 
            = link_to breadcrumb[:label], breadcrumb[:path], class: "text-dark font-weight-bold text-decoration-none"

app/views/shared/_footer.html.slim
footer.container.fixed-bottom.bg-light.pt-2.pb-2.navbar-light.mt-5
  .row.justify-content-between
    p.font-weight-bold.text-muted.col-lg-3.nav-link.mb-0.text-center = t('global.footer.string')
    nav.col-lg-4.d-flex.justify-content-center
      ul.navbar-nav.flex-row.justify-content-end
        li.nav-item.mr-4= link_to t('global.footer.about'), about_path, class: "nav-link font-weight-bold"
        li.nav-item.mr-4= link_to t('global.footer.contacts'), contacts_path, class: "nav-link font-weight-bold"
        li.nav-item= link_to t('global.footer.softserve'), "https://www.softserveinc.com/uk-ua", target: '_blank', class: "nav-link font-weight-bold"
  = any_login_here if defined?(AnyLogin)

app/views/shared/_header.html.slim
header.navbar.navbar-dark.bg-dark.fixed-top.navbar-expand-md
  .container.pl-2
    = link_to t('global.header.logo'), welcome_path, id: "logo", class: "navbar-brand font-weight-bold d-block m-2 position-relative"
    button.navbar-toggler aria-controls="navbar_supported_content_header" aria-expanded="true" aria-label="toggle navigation" data-target="#navbar_supported_content_header" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbar_supported_content_header.collapse.navbar-collapse.justify-content-between
    .d-flex.flex-md-row.flex-column
      ul.navbar-nav
        - if user_signed_in?
          li.nav-item = link_to t('global.header.posts'), posts_path, class: "nav-link"
          li.nav-item = link_to t('global.header.attachments'), attachments_path, class: "nav-link"
          li.nav-item = link_to t('global.header.albums'), albums_path, class: "nav-link"
          li.nav-item = link_to t('global.header.person'), '#', class: "nav-link"
          li.nav-item = link_to t('global.header.invite'), invitations_path, class: "nav-link"
          li.nav-item = link_to t('global.header.important_dates'), important_dates_path, class: "nav-link"
          li.nav-item = link_to t('global.header.locations'), locations_path, class: "nav-link"
    .d-flex.flex-md-row.flex-column
      ul.navbar-nav.align-items-center
        - if user_signed_in?
          .dropdown.show
            #dropdown_menu_link.btn.dropdown-toggle[ role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ]
              = image_tag current_user.gravatar, class: "rounded-circle gravatar"
            ul.dropdown-menu.text-black[aria-labelledby="dropdown_menu"]
              li.small.m-2 = t('global.header.signed_in_as')
              li.nav-link.dropdown-item.nav-item.text-dark.disabled = current_user.email
              .dropdown-divider
              li.nav-link.dropdown-item.nav-item = link_to t('global.header.edit_profile'), edit_user_registration_path, class: "text-dark"
              .dropdown-divider
              li.nav-link.dropdown-item.nav-item = link_to t('global.header.log_out'), destroy_user_session_path, method: :delete, class: "text-dark"
        - else
          li.nav-item.m-2= link_to t('global.header.sign_up'), new_user_registration_path, class: "nav-link"
          li.nav-item.m-2= link_to t('global.header.log_in'), new_user_session_path, class: "nav-link"
    .dropdown.d-flex.align-items-center
      #dropdown_menu_button.btn.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
        = image_tag "language.png"
      ul.dropdown-menu.border.border-dark aria-labelledby="dropdown_menu_button"
        - I18n.available_locales.each do |locale|
          li.nav-link.text-muted= link_to_unless current_locale?(locale), I18n.t("global.header.#{locale}_switch"), locale_path(locale), method: :put, class: "text-dark text-decoration-none"

app/views/shared/_messages.html.slim
- flash.each do |name, message|
  div class=("alert #{bootstrap_class_for(name)}")
    button.close data-dismiss="alert" &times;
    = message

app/views/shared/_modal_window.html.slim
#modal-window.modal tabindex="-1"
  .modal-dialog
    .modal-content