config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for locale
  put 'locales/:locale', to: 'locales#update', as: :locale,
                         constraints: { locale: /#{I18n.available_locales.join('|')}/ }

  # Regular routes
  get 'welcome', to: 'welcome_pages#welcome', as: :welcome
  get 'about', to: 'welcome_pages#about', as: :about
  get 'contacts', to: 'welcome_pages#contacts', as: :contacts

  concern :attachable do
    resources :attachments, only: :create
  end
  resources :attachments do
    member do
      post 'add_attachment_to_album'
    end
  end
  resources :albums, concerns: [:attachable]

  # Resource routes
  resources :posts
  resources :locations
  resources :important_dates

  # Invitations routes
  get 'invitations', to: 'invitations#index', as: :invitations

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'welcome_pages#welcome', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  include CreatableBy

  has_many :attachment_relations, dependent: :destroy
  has_many :albums, through: :attachment_relations, source: :attachable,
                    source_type: 'Album'

  mount_uploader :file, FileUploader
  validates :file, presence: true

  before_create :set_original_file_name

  private

  def set_original_file_name
    self.original_filename = file.send(:original_filename)
  end
end

app/controllers/attachment_controller.rb
# frozen_string_literal: true

class AttachmentController < ApplicationController
  before_action :set_attachment, only: %i[show edit update destroy]

  def index
    @attachments = Attachment.by_user(current_user)
    @attachments = @attachments.where("keywords LIKE '%#{params[:tag]}%'") if params[:tag]
  end

  def show
    @albums = Album.by_user(current_user)
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.by_user(current_user).new(file_params)
    if @attachment.save
      redirect_to @attachment, success: t('attachment.controller.create')
    else
      flash[:danger] = t('attachment.controller.create_error')
      render :new
    end
  end

  def update
    if @attachment.update(file_params)
      redirect_to @attachment, success: t('attachment.controller.update')
    else
      flash[:danger] = t('attachment.controller.update_error')
      render :edit
    end
  end

  def destroy
    @attachment.destroy
    redirect_to attachment_index_path, success: t('attachment.controller.destroy')
  end

  def add_attachment_to_album
    album_id = params[:attachmentRelation][:album]
    attachment_id = params[:attachmentRelation][:attachmentId]
    AttachmentRelation.find_or_create_by(attachment_id: attachment_id, attachable_id: album_id,
                                         attachable_type: 'Album')
  end

  private

  def set_attachment
    @attachment = Attachment.by_user(current_user).find(params[:id])
  end

  def file_params
    params.require(:attachment).permit(:file, :keywords, :notes, :place, :date, :original_filename)
  end
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < DashboardController
  before_action :set_attachment, only: %i[show edit update destroy add_attachment_to_album]

  def index
    add_breadcrumb(t('.breadcrumb'))
    @attachments = policy_scope(Attachment)
    @attachments = @attachments.where('keywords LIKE ?', "%#{params[:tag]}%") if params[:tag].present?
    @attachments = authorize @attachments.paginate(page: params[:page])
  end

  def show
    add_breadcrumb(@attachment.original_filename)
    @albums = policy_scope(Album)
  end

  def new
    add_breadcrumb(t('.breadcrumb'))
    @attachment = policy_scope(Attachment).new
  end

  def create
    add_breadcrumb(t('.breadcrumb'))
    @attachment = authorize policy_scope(Attachment).new(file_params)
    if @attachment.save
      redirect_to @attachment, success: t('attachments.controller.create')
    else
      flash[:danger] = t('attachments.controller.create_error')
      render :new
    end
  end

  def edit
    add_breadcrumb(@attachment.original_filename, attachment_path(@attachment))
    add_breadcrumb(t('.breadcrumb'))
  end

  def update
    add_breadcrumb(@attachment.original_filename, attachment_path(@attachment))
    add_breadcrumb(t('.breadcrumb'))
    if @attachment.update(file_params)
      redirect_to @attachment, success: t('attachments.controller.update')
    else
      flash[:danger] = t('attachments.controller.update_error')
      render :edit
    end
  end

  def destroy
    @attachment.destroy
    redirect_to attachments_path, success: t('attachments.controller.destroy')
  end

  def add_attachment_to_album
    album = policy_scope(Album).find(params[:attachment_relation][:album])
    album.attachments << @attachment
    flash.now[:notice] = t('attachments.attachment_to_album')
  end

  private

  def set_attachment
    @attachment = authorize policy_scope(Attachment).find(params[:id])
  end

  def file_params
    params.require(:attachment).permit(:file, :keywords, :notes, :place, :date, :original_filename)
  end
end

app/views/attachments/_all_attachments.html.slim
= will_paginate @attachments, list_classes: %w(pagination justify-content-center)
table.table.table-bordered
  thead
    tr.text-center
      th scope="col" = t('attachments.file_name')
      th scope="col" = t('attachments.file')
      th scope="col" = t('attachments.notes')
      th scope="col" = t('common.actions')
  tbody
    - @attachments.each do |image|
        tr.text-center
          td = image.original_filename
          td = image_tag image.file.url(:small), alt: "#{image.original_filename}" if image.file?
          td = image.notes
          td
            =< link_to attachment_path(image), class: 'btn btn-info', title: t('common.show') do
              i.fas.fa-eye
            =< link_to edit_attachment_path(image), class: 'btn btn-primary', title: t('common.edit') do
              i.fas.fa-edit
            =< link_to attachment_path(image), class: 'btn btn-danger', title: t('common.delete'), method: :delete, data: { confirm: t('common.confirmation') } do
              i.fas.fa-trash-alt
            =< link_to t('attachments.add_to_album'), attachment_path(image), remote: true, class: 'btn btn-primary'
= will_paginate @attachments, list_classes: %w(pagination justify-content-center)

app/views/attachments/_attachments.html.slim
table.table.table-bordered
  thead
    tr.text-center
      th scope="col" = t('attachments.file_name')
      th scope="col" = t('attachments.file')
      th scope="col" = t('attachments.notes')
      th colspan="4" scope="col" = t('common.actions')
  tbody
    - @attachments.each do |image|
        tr.text-center
          td = image.original_filename
          td = image_tag image.file.url(:small), alt: "#{image.original_filename}" if image.file?
          td = image.notes
          td = link_to t('common.show'), attachment_path(image), class: 'btn btn-info'
          td = link_to t('common.edit'), edit_attachment_path(image), class: 'btn btn-primary'
          td = link_to t('common.delete'), attachment_path(image), class: 'btn btn-danger', method: :delete, data: { confirm: t('common.confirmation') }
          td = link_to t('attachments.add_to_album'), attachment_path(image), remote: true, class: 'btn btn-primary'
#modal-window.modal tabindex="-1"
  .modal-dialog
    .modal-content

app/views/attachments/_modal.html.slim
.modal-header
  h5.modal-title
    = t('common.add')
    =< @attachment.original_filename
  button.close aria-label="Close" data-dismiss="modal" type="button"
    span aria-hidden="true" ×
.modal-body
  = simple_form_for :attachment_relation, url: add_attachment_to_album_path, remote: true do |f|
    = f.hidden_field :attachment_id, value: @attachment.id
    = f.input :album, collection: @albums.each { |name| name  }
    = f.submit t('common.save'), class: 'btn btn-primary'

app/views/attachments/_modal_content.html.slim
.modal-header
  h5.modal-title
    = t('common.add')
    =< @attachment.original_filename
  button.close aria-label="Close" data-dismiss="modal" type="button"
    span aria-hidden="true" ×
.modal-body
  = simple_form_for :attachment_relation, url: add_attachment_to_album_attachment_path, remote: true do |f|
    = f.input :album, collection: @albums.reject { |album| @attachment.albums.include?(album) }
    = f.submit t('common.save'), class: 'btn btn-primary'

app/views/attachments/add_attachment_to_album.js.erb
$("table").before("<%= j render 'layouts/messages' %>");
$('#modal-window').modal('hide');

app/views/attachments/edit.html.slim
- title t('attachments.edit.page_title', title: @attachment.original_filename)
= simple_form_for @attachment do |f|
  h3 = t('.edit_file')
  = f.input :original_filename, placeholder: t('attachments.file_name')
  = f.input :keywords, placeholder: t('attachments.keywords')
  = f.input :notes, placeholder: t('attachments.notes')
  = f.input :place, placeholder: t('attachments.place')
  = f.input :date, as: :date, html5: true
  = f.submit t('global.forms.submit'), class: 'btn btn-primary mt-3'
  = link_to t('common.back'), :back, class: 'btn btn-secondary mt-3 ml-3'

app/views/attachments/index.html.slim
- title t('attachments.index.page_title')
= render 'attachments/all_attachments'
= link_to t('.create_file'), new_attachment_path, class:"btn btn-success"

app/views/attachments/new.html.slim
- title t('attachments.new.page_title')
= simple_form_for @attachment do |f|
  h1 = t('.create_file')
  = f.input :keywords, placeholder: t('attachments.keywords')
  = f.input :notes, placeholder: t('attachments.notes')
  = f.input :place, placeholder: t('attachments.place')
  = f.input :date, as: :date, html5: true
  .input-group.mb-3
    .custom-file
      = f.file_field :file, class: "custom-file-input"
      label.custom-file-label = t('.add_file')
    .input-group-append
      .input-group-text
        = t('.upload')
  = f.submit t('global.forms.submit'), class: 'btn btn-primary mt-3'
  = link_to t('common.back'), :back, class: 'btn btn-secondary mt-3 ml-3'

app/views/attachments/show.html.slim
- title t('attachments.show.page_title', title: @attachment.original_filename)
- if @attachment.file?
  h3 = @attachment.original_filename
  = image_tag @attachment.file.url(:large), class: 'mb-3', alt: @attachment.original_filename
  h3.text-uppercase = t('.information')
  p
    strong => t('.keywords')
    - if @attachment.keywords?
      - @attachment.keywords.split(',').each do |keyword|
        = link_to keyword, attachments_path(tag: keyword), class: 'badge badge-pill badge-info mr-2'
  p
    strong => t('.notes')
    = @attachment.notes
  p
    strong => t('.place')
    = @attachment.place
  p
    strong => t('.date')
    = l(@attachment.date, format: :date) if @attachment.date?
  p
    strong = t('.albums')
    - @attachment.albums.each do |album|
      = link_to album_path(album), class: 'd-table-cell text-center pr-3' do
        = image_tag album.attachments.last.file.url(:small), alt: "#{album.attachments.last.original_filename}"
        span.d-block = album.name
  h3.text-uppercase = t('.information')
  p
    strong => t('.type')
    = @attachment.file.content_type
  p
    strong => t('.width')
    = @attachment.file.width
    =< t('.px')
  p
    strong => t('.height')
    = @attachment.file.height
    =< t('.px')
  p
    strong => t('.size')
    = number_to_human_size(@attachment.file.size)
  p
    strong => t('.downloaded')
    = @attachment.created_by.email
  p
    = link_to t('.donwload'), @attachment.file.url, download: @attachment.original_filename, class: 'btn btn-info'
  = link_to t('common.edit'), edit_attachment_path(@attachment), class: "btn btn-primary"
  = link_to t('common.delete'), attachment_path(@attachment), class: 'btn btn-danger ml-3', method: :delete, data: { confirm: t('common.confirmation') }
  = link_to t('common.back'), :back, class: 'btn btn-secondary ml-3'

app/views/attachments/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'attachments/modal_content' %>");
$("#modal-window").modal();