config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for locale
  put 'locales/:locale', to: 'locales#update', as: :locale,
                         constraints: { locale: /#{I18n.available_locales.join('|')}/ }

  # Regular routes
  get 'welcome', to: 'welcome_pages#welcome', as: :welcome
  get 'about', to: 'welcome_pages#about', as: :about
  get 'contacts', to: 'welcome_pages#contacts', as: :contacts

  concern :attachable do
    resources :attachments, only: :create
  end
  resources :attachments do
    member do
      post 'add_attachment_to_album'
    end
  end
  resources :albums, concerns: [:attachable]

  # Resource routes
  resources :posts
  resources :locations
  resources :important_dates

  # Invitations routes
  get 'invitations', to: 'invitations#index', as: :invitations

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'welcome_pages#welcome', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/important_date.rb
# frozen_string_literal: true

class ImportantDate < ApplicationRecord
  include CreatableBy

  validates :event_name, presence: true, length: { minimum: 3, maximum: 255 }
  validates :event_date, presence: true
  validates :description, presence: true, length: { minimum: 3, maximum: 500 }
end

app/controllers/important_dates_controller.rb
# frozen_string_literal: true

class ImportantDatesController < DashboardController
  before_action :set_important_date, only: %i[show edit update destroy]

  def index
    add_breadcrumb(t('important_dates.index.breadcrumb'))
    @important_dates = authorize collection.paginate(page: params[:page])
  end

  def show
    add_breadcrumb(@important_date.event_name)
  end

  def new
    add_breadcrumb(t('important_dates.new.breadcrumb'))
    @important_date = collection.new
  end

  def edit
    add_breadcrumb(@important_date.event_name, important_date_path(@important_date))
    add_breadcrumb(t('important_dates.edit.breadcrumb'))
  end

  def create
    add_breadcrumb(t('important_dates.new.breadcrumb'))
    @important_date = authorize collection.new(important_date_params)
    if @important_date.save
      flash[:notice] = t('.controller.create')
      redirect_to @important_date
    else
      render 'new'
    end
  end

  def update
    add_breadcrumb(@important_date.event_name, important_date_path(@important_date))
    add_breadcrumb(t('important_dates.edit.breadcrumb'))
    if @important_date.update(important_date_params)
      flash[:notice] = t('.controller.update')
      redirect_to @important_date
    else
      render 'edit'
    end
  end

  def destroy
    @important_date.destroy
    flash[:notice] = t('.controller.destroy')
    redirect_to important_dates_url
  end

  private

  def collection
    policy_scope(ImportantDate)
  end

  def set_important_date
    @important_date = authorize collection.find(params[:id])
  end

  def important_date_params
    params.require(:important_date).permit(:event_name, :event_date, :description)
  end
end

app/views/important_dates/_form.html.slim
= simple_form_for(important_date) do |f|
  = f.input :event_name, placeholder: t('.event_placeholder')
  = f.input :event_date, html5: true
  = f.input :description, placeholder: t('.description_placeholder')
  = f.submit t('global.forms.submit'), class:"btn btn-primary"

app/views/important_dates/edit.html.slim
- title t('.page_title', event_name: @important_date.event_name)
h1 = t('.title')
= render 'important_dates/form', important_date: @important_date
= link_to t('.show'), @important_date, class:"btn btn-xs btn-success mt-3"
= link_to t('.back'), important_dates_path, class:"btn btn-xs btn-info mt-3 ml-3"

app/views/important_dates/index.html.slim
- title t('.page_title')
h1 = t('.main_title')

= will_paginate @important_dates, list_classes: %w(pagination justify-content-center)

table.table.table-bordered.table-hover
  thead
    tr
      th scope="col" = t('.event_name')
      th scope="col" = t('.event_date')
      th scope="col" = t('.description')
      th scope="col" = t('.actions')
  tbody
    - @important_dates.each do |important_date|
      tr
        td = important_date.event_name
        td = important_date.event_date
        td = important_date.description
        td.col-sm-3
          =< link_to important_date, class:"btn btn-xs btn-info", title: t('.show') do
            i.fas.fa-eye
          =< link_to edit_important_date_path(important_date), class:"btn btn-xs btn-success", title: t('.edit') do
            i.fas.fa-edit
          =< link_to important_date, data: { confirm: t('.confirmation') }, class:"btn btn-xs btn-danger", title: t('.destroy'), method: :delete do
            i.fas.fa-trash-alt
= link_to t('.new_important_date'), new_important_date_path, class:"btn btn-success"

= will_paginate @important_dates, list_classes: %w(pagination justify-content-center)

app/views/important_dates/new.html.slim
- title t('.page_title')
h1 = t('.title')
= render 'important_dates/form', important_date: @important_date
= link_to t('.back'), important_dates_path, class:"btn btn-xs btn-info mt-3"

app/views/important_dates/show.html.slim
- title t('.page_title', event_name: @important_date.event_name)
p
  strong = t('.event_name')
  = @important_date.event_name
p
  strong = t('.event_date')
  = @important_date.event_date
p
  strong = t('.description')
  = @important_date.description
= link_to t('.edit'), edit_important_date_path(@important_date), class:"btn btn-xs btn-success"
= link_to t('.back'), important_dates_path, class:"btn btn-xs btn-info ml-3"